name: Deploy GalVPN's React App to GitHub Pages

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./client

        steps:
            - name: Checkout repository (1)
              uses: actions/checkout@v4

            - name: Set up Node.js (2)
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies (3)
              run: npm install

            - name: Build project (4)
              run: npm run build
              env:
                  PROD_URL: ${{ secrets.PROD_URL }}

            - name: Upload build artifacts (5)
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./client/dist

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
