name: Deploy GalVPN's React App to GitHub Pages

on:
    push:
        branches:
            - master

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: galvpn/client

        steps:
            - name: Checkout repository (1)
              uses: actions/checkout@v4

            - name: Set up Node.js (2)
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: galvpn/client/package-lock.json

            - name: Install dependencies (3)
              run: npm install

            - name: Build project (4)
              run: npm run build

            - name: Upload build artifacts (5)
              uses: actions/upload-pages-artifact@v3
              with:
                  path: galvpn/client/dist

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
